### PR TITLE
Mandatory update token

### PR DESCRIPTION
**Pull request by Jackclarify**
update the validic_user table in mandatory when server starting

### CODE REVIEW

**Comment by JoeyLi-1** [comment]
Hi Erik, please help to merge this PR. We are waiting for this to verify PLT-1484. @talvola

**Comment by Jackclarify** [comment]
Oh no, I will add an ENV condition to decide whether it truncates validic_user table or not.

**Comment by Jackclarify** [comment]
Hi Erik, I have add a 'MANDATORY=true' condition to decide whether we will update the table. If we don't pass the parameter,we will use the original data.  Is it okay?

**Comment by talvola** [comment]
That sounds good for now.   thanks

**Pull request merged**
